<a href="https://colab.research.google.com/github/kookie14/Optimization/blob/main/phuong_phap_tinh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Gausse Elimination Method


In [ ]:
def gaussy(A, b, n):
    l = [0 for x in range(n)]
    s = [0.0 for x in range(n)]
    for i in range(n):
        l[i] = i
        smax = 0.0
        for j in range(n):
            if abs(A[i][j]) > smax:
                smax = abs(A[i][j])
        s[i] = smax

    for i in range(n - 1):
        rmax = 0.0
        for j in range(i, n):
            ratio = abs(A[l[j]][i]) / s[l[j]]
            if ratio > rmax:
                rmax = ratio
                rindex = j
        temp = l[i]
        l[i] = l[rindex]
        l[rindex] = temp
        for j in range(i + 1, n):
            multiplier = A[l[j]][i] / A[l[i]][i]
            for k in range(i, n):
                A[l[j]][k] = A[l[j]][k] - multiplier * A[l[i]][k]
            b[l[j]] = b[l[j]] - multiplier * b[l[i]]

    x = [0.0 for y in range(n)]
    x[n - 1] = b[l[n - 1]] / A[l[n - 1]][n - 1]
    for j in range(n - 2, -1, -1):
        summ = 0.0
        for k in range(j + 1, n):
            summ = summ + A[l[j]][k] * x[k]
        x[j] = (b[l[j]] - summ) / A[l[j]][j]

    print ("Nghiệm xấp xỉ [", end="")
    for i in range(n):
        if i != (n - 1):
            print(x[i], ",", end="")
        else:
            print(x[i], "].")

matrix0 = [[1, -1, 2 ,-1], [2,-2,3,-3],[1,1,1,0],[1,-1,4,3]]
vector0 = [-8,-20,-2,4]

matrix1 = [[3.0, 2.0, -5.0], [2.0, -3.0, 1.0], [1.0, 4.0, -1.0]]
vector1 = [0.0, 0.0, 4.0]

gaussy(matrix0, vector0, 4)
gaussy(matrix1, vector1, 3)

Nghiệm xấp xỉ [-6.999999999999998 ,2.999999999999999 ,1.9999999999999993 ,2.0000000000000004 ].
Nghiệm xấp xỉ [0.9999999999999999 ,1.0 ,1.0000000000000002 ].


# 2. Gauss-Seidel Method

In [ ]:
def gaussSeidel(A, b, x, N, tol):
    maxIterations = 1000000
    xprev = [0.0 for i in range(N)]
    for i in range(maxIterations):
        for j in range(N):
            xprev[j] = x[j]
        for j in range(N):
            summ = 0.0
            for k in range(N):
                if (k != j):
                    summ = summ + A[j][k] * x[k]
            x[j] = (b[j] - summ) / A[j][j]
        diff1norm = 0.0
        oldnorm = 0.0
        for j in range(N):
            diff1norm = diff1norm + abs(x[j] - xprev[j])
            oldnorm = oldnorm + abs(xprev[j])  
        if oldnorm == 0.0:
            oldnorm = 1.0
        norm = diff1norm / oldnorm
        if (norm < tol) and i != 0:
            print("nghiệm xấp xĩ là: [", end="")
            for j in range(N - 1):
                print(x[j], ",", end="")
            print(x[N - 1], "]. mat ", i + 1, "vong lap.")
            return
    print("không hội tụ")

matrix2 = [[3.0, 1.0], [2.0, 6.0]]
vector2 = [5.0, 9.0]
guess = [0.0, 0.0]

matrix3 = [[9.0, -3.0], [-2.0, 8.0]]
vector3 = [6.0, -4.0]

matrix4 = [[1.0, -3.0], [-2.0, 8.0]]

gaussSeidel(matrix2, vector2, guess, 2, 0.00000000000001)
gaussSeidel(matrix3, vector3, guess, 2, 0.00000000000001)
gaussSeidel(matrix4, vector3, guess, 2, 0.00000000000001)

Khoảng hội tụ là: [1.3125000000000018 ,1.0624999999999993 ]. mat  16 vong lap.
Khoảng hội tụ là: [0.5454545454545457 ,-0.36363636363636354 ]. mat  15 vong lap.
Khoảng hội tụ là: [17.99999999999958 ,3.999999999999895 ]. mat  109 vong lap.


# 3. Cholesky Method

In [ ]:
import math
import numpy as np

MAX = 100;
 
def Cholesky_Decomposition(matrix, n, b):
 
    lower = [[0 for x in range(n + 1)]
                for y in range(n + 1)];
    L = [[0 for x in range(n)]
              for y in range(n )];

    # phân tích ma trận
    # thành ma trận tam giác dưới
    for i in range(n):
        for j in range(i+1):
            sum1 = 0;
            sum3 = 0;
            sum4 = 0;
 
            # tính tổng 
            if (j == i):
                for k in range(j):
                    sum1 += pow(lower[j][k], 2);
                lower[j][j] = float(math.sqrt(matrix[j][j] - sum1));
            else:
                 
                # Đánh giá L[i,j]
                # sử dụng L[j, j]
                for k in range(j):
                    sum1 += (lower[i][k] *lower[j][k]);
                if(lower[j][j] > 0):
                    lower[i][j] = float((matrix[i][j] - sum1) /
                                               lower[j][j]);
          
    print("Ma trận tam giác dưới\t\tMa trận chuyển vị");
    for i in range(n):
         
        # Ma trận tam giác dưới
        for j in range(n):
            print(lower[i][j], end = "\t");
            L[i][j] = lower[i][j]
        print("", end = "\t");
         
        # Ma trận chuyển vị của ma trận tam giác dưới
        for j in range(n):
            print(lower[j][i], end = "\t");
        print("");
    return L

def solver(L,U,b):
  L=np.array(L, float)
  U=np.array(U, float)
  b=np.array(b, float)

  n,_=np.shape(L)
  y=np.zeros(n)
  x=np.zeros(n)

# Giai PT Ly = b
  for i in range(n):
    sumj=0
    for j in range(i):
      sumj += L[i,j]*y[j]
    y[i]=(b[i]-sumj)/L[i,i]

# Gia Ux = y 
  for i in range(n-1, -1, -1):
    sumj=0
    for j in range(i+1,n):
      sumj += U[i,j] * x[j]
    x[i]=(y[i]-sumj)/U[i,i]
  return x


# ví dụ
n = 3;
matrix = [[4, 2, 14],
          [2, 17, -5],
          [14, -5, 83]];
b = [14, -101, 155]
L = Cholesky_Decomposition(matrix, n, b);
print(L)
U = np.transpose(L)
print(U)
print("Nghiệm x là: ")
print((solver(L,U,b)))


 

Ma trận tam giác dưới		Ma trận chuyển vị
2.0	0	0		2.0	1.0	7.0	
1.0	4.0	0		0	4.0	-3.0	
7.0	-3.0	5.0		0	0	5.0	
[[2.0, 0, 0], [1.0, 4.0, 0], [7.0, -3.0, 5.0]]
[[ 2.  1.  7.]
 [ 0.  4. -3.]
 [ 0.  0.  5.]]
Nghiệm x là: 
[ 3. -6.  1.]


# 4. Gauss-Jordan Method





In [ ]:
import numpy as np

def swap(matrix, row,k):
	temp = matrix[k]
	if (k != (row-1)):
		matrix[k] = matrix[k+1]
		matrix[k+1] = temp
		normal(matrix,k,matrix[k][k],row+1)
		eliminate(matrix,k,row,row+1)

def normal(matrix,k, a,col):
	if (a!=0):
		for j in range(col):
			matrix[k][j] = matrix[k][j]/a
	else:
		swap(matrix,col-1,k)

def eliminate(matrix, k, row,col):
	for i in range(row):
		if (i!=k):
			b = matrix[i][k]
			for j in range(col):
				matrix[i][j] = matrix[i][j]-b*matrix[k][j]

## ví dụ:
matrix  = [[1, -1, 2 ,-1, -8], [2,-2,3,-3, -20],[1,1,1,0, -2],[1,-1,4,3, 4]]
row = 4
col = 5
for i in range(row):
  for j in range(col):
  	if(i==j):
  		      a = matrix[i][j]
	  	      normal(matrix,i,a,col)
	  	      eliminate(matrix,i,row,col)
for i in range(len(matrix)):
	print(matrix[i])


[1.0, 0.0, 0.0, 0.0, -7.0]
[0.0, 1.0, 0.0, 0.0, 3.0]
[-0.0, -0.0, 1.0, 0.0, 2.0]
[0.0, 0.0, 0.0, 1.0, 2.0]


# Solutions of Equations in One Variable

*   1. Fixed-point Iteration
*   2. Newton's Method
*   3. Secant Method
*   4. False Position method



# Fixed-point Iteration

In [ ]:
import numpy as np

def g(p):
    return((3*p**2+3)**(1/4))

Tol = 10**(-2)
N0 = 10
p0 = 1
i = 1

while i<= N0:
    p = g(p0)
    FP = g(p)
    if np.abs(p-p0)< Tol:
        print("p = "+str(p)+ " after "+str(i)+" iterations")
        break
    i = i+1
    print(p)
    p0 = p
if i > N0: 
    print("Method failed after " + str(N0)+ " iterations")

1.5650845800732873
1.79357287863573
1.8859437430173158
1.9228478439840826
1.9375075399574273
p = 1.9433169298986768 after 6 iterations


# Newton Method

In [ ]:
def newtonsmethod(p0, n, tol):
    def f(p):
        return((3*p**2+3)**(1/4))

    def df(p):
        return(3/2*p*((3*p**2+3)**(-3/4)))
    i = 1
    while i <= n:
        p = p0 - (f(p0)/df(p0))
        if abs(p- p0) < tol:
            print("x = "+str(p)+ " after "+str(i)+" iterations")
            break
        i =i+1
        print(p)
        p0 = p
    if i > n: 
        print("Method failed after " + str(n)+ " iterations")

newtonsmethod(1, 10, 10**(-2))

-3.0
3.666666666666667
-4.212121212121213
4.6869413560061055
-5.113658877751304
5.504768266901541
-5.868089646300087
6.20891606861983
-6.531033484590083
6.837263732026262
Method failed after 10 iterations


# Secant Method

In [ ]:
from math import cos
# apply with f  = cosx - x
def secantMethod(p0, p1, tol, n):
    def f(x):
        return cos(x) - x
    i = 2
    q0 = f(p0)
    q1 = f(p1)
    while i <= n:
        p = p1 - q1*(p1-p0)/(q1-q0)
        if abs(p-p1) < tol:
            print("x = "+ str(p)+ " after " + str(i) + " iterations")
            break
        i = i+1
        print(p)
        p0 = p1
        q0 = q1
        p1 = p
        q1 = f(p)
    if i > n: 
        print("Method failed after " + str(n)+ " iterations")

## ví dụ
        
secantMethod(0,3.14/2, 10**(-2), 10)

0.6110842890046084
0.7232860813113391
0.7395663230305634
x = 0.7390834410483108 after 5 iterations


# False Position Method

In [ ]:
from math import cos
# apply with f  = cosx - x
def flasePosition(p0, p1, tol, n):
    def f(x):
        return cos(x) - x
    i = 2
    q0 = f(p0)
    q1 = f(p1)
    while i <= n:
        p = p1 - q1*(p1-p0)/(q1-q0)
        print(p)
        if abs(p-p1) < tol:
            print("x = "+ str(p)+ " after " + str(i) + " iterations")
            break
        i = i+1
        q = f(p)
        if(q*q1 < 0):
            p0 = p1
            q0 = q1
        p1 = p
        q1 = q
    if i > n: 
        print("Method failed after " + str(n)+ " iterations")
# ví dụ
flasePosition(0,3.14/2, 10**(-2), 10)
        

0.6110842890046084
0.7232860813113391
0.737268633985274
0.7388781713239154
x = 0.7388781713239154 after 5 iterations
